# Generated by Django 5.0.2 on 2026-05-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ai_provider',
            field=models.CharField(default='gemini', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bot_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='llm_model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
