# Generated by Django 5.0.2 on 2026-02-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], default='whatsapp', max_length=20),
        ),
    ]
