# Generated by Django 5.0.2 on 2026-04-15 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(help_text="Human-readable label (e.g. 'Main WhatsApp Line').", max_length=255),
        ),
        migrations.AlterField(
            model_name='channel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='verify_token',
            field=models.CharField(blank=True, help_text='Token used to verify Meta webhook subscriptions.', max_length=128),
        ),
        migrations.AlterField(
            model_name='channel',
            name='wa_phone_id',
            field=models.CharField(blank=True, help_text='Phone Number ID from Meta Business Manager.', max_length=128),
        ),
        migrations.AlterField(
            model_name='channel',
            name='wa_token',
            field=models.CharField(blank=True, help_text='Permanent access token. Encrypt before production.', max_length=512),
        ),
    ]
